### ISSUE TITLE
[TWW] Support for Patch 11.0

### ISSUE THREAD

**Issue by Dathwada** [TheKrowi/Krowi_WorldMapButtons#2]
Since Blizzard added the new Map Legend Button in the last build for The War Within you might want to also hook this default button.

[WorldMapShowLegendButtonMixin](https://github.com/Gethe/wow-ui-source/blob/5ad5491dcf7bd4e17bd5cc46a6cb8c3c8f34bbad/Interface/AddOns/Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua#L406)
```lua
if WorldMapShowLegendButtonMixin and f.OnLoad == WorldMapShowLegendButtonMixin.OnLoad then
	f.KrowiWorldMapButtonsIndex = #lib.Buttons;
	tinsert(lib.Buttons, f);
end
```

![ss+(2024-06-27+at+06 12 05)](https://github.com/TheKrowi/Krowi_WorldMapButtons/assets/57680823/2cdc0b8e-a83f-4c01-9345-9991307a6ccd)

**Comment by TheKrowi** [comment]
Resolved in 1.4.6
